networks:
  mynetwork:
    driver: bridge
services:
  bitcoind:
    restart: always
    networks:
      - mynetwork
    build:
      context: ./bitcoind
      args:
        BUILD_BITCOINCORE_VERSION: ${BUILD_BITCOINCORE_VERSION}
        BUILD_BITCOIN_CORE_SIGNATURE: ${BUILD_BITCOIN_CORE_SIGNATURE}
    working_dir: /home/user01
    user: user01
    volumes:
      - ${PERSISTENT_DATA_DIR}/bitcoind:/home/user01/.bitcoin:rw
      - ./bitcoind/bitcoin.conf:/home/user01/.bitcoin/bitcoin.conf:rw
    stdin_open: true
    tty: true
    command: sh -c "/opt/bitcoin/bin/bitcoind"

  electrs:
    networks:
      - mynetwork
    build:
      context: ./electrs
      args:
        BUILD_ELECTRS_VERSION: ${BUILD_ELECTRS_VERSION}
    volumes:
      - ${PERSISTENT_DATA_DIR}/bitcoind:/home/user01/.bitcoin
      - ${PERSISTENT_DATA_DIR}/electrs-data:/home/user01/electrs-data
      - ./electrs/electrs-config.toml:/home/user01/electrs-config.toml
    healthcheck:
      timeout: 60s
    restart: always
    stdin_open: true
    tty: true
    working_dir: /home/user01/electrs-data
    command: sh -c "electrs --conf /home/user01/electrs-config.toml"
    #command: sh -c "electrs --conf /home/user01/electrs-config.toml; tail -F somethingToKeepOpen"

  nginx:
    networks:
      - mynetwork
    build:
      context: ./nginx
    # restart: always
    ports:
      - "50002:50002"
      - "50003:50003"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site-default:/etc/nginx/sites-enabled/default
      - ./nginx/electrs-reverse-proxy.conf:/etc/nginx/streams-enabled/electrs-reverse-proxy.conf
      - ./nginx/files-runtime:/home/user01/files-runtime
      - ./nginx/start.sh:/home/user01/start.sh
    command: sh -c "chmod +x /home/user01/start.sh && /home/user01/start.sh"
    healthcheck:
      timeout: 60s
    restart: always

  btc-rpc-explorer:
    networks:
      - mynetwork
    image: svdkrgsfa/btc-rpc-explorer:latest
    volumes:
      - ${PERSISTENT_DATA_DIR}/bitcoind/.cookie:/tmp/.cookie
    environment:
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_PORT: 3012
      BTCEXP_BITCOIND_HOST: bitcoind
      BTCEXP_BITCOIND_PORT: 29123
      BTCEXP_BITCOIND_COOKIE: /tmp/.cookie
      BTCEXP_SLOW_DEVICE_MODE: false
      BTCEXP_PRIVACY_MODE: false
      BTCEXP_NO_RATES: false
      BTCEXP_UI_THEME: dark

      #BTCEXP_ADDRESS_API: blockchain.com
      BTCEXP_ADDRESS_API: electrum
      BTCEXP_ELECTRUM_TXINDEX: true
      BTCEXP_ELECTRUM_SERVERS: tcp://electrs:50001
    ports:
      - "3012:3012"

# privacy-router:
#   container_name: internetrouter
#   build: 
#     context: .
#     dockerfile: Dockerfile-internetrouter
#   volumes:
#     - ./openvpn.conf:/data/.openvpn/openvpn.confg

# rdpserver:
#   networks:
#     - mynetwork
#   build:
#     context: ./rdpserver
#   # restart: always
#   ports:
#     - "13389:3389"